<script setup lang="ts">
import { Authenticator } from "@aws-amplify/ui-vue";
import type { Schema } from "~/amplify/data/resource";

// create a reactive reference to the array of todos
const todos = ref<Schema["Todo"]["type"][]>([]);

async function listTodos() {
  try {
    // `$Amplify` is generated by Nuxt according to the `provide` key in the plugins
    // fetch all todos
    const { data } =
      await useNuxtApp().$Amplify.GraphQL.client.models.Todo.list();
    todos.value = data;
  } catch (error) {
    console.error("Error fetching todos", error);
  }
}

// fetch todos when the component is mounted
onMounted(() => {
  listTodos();
});
</script>

<template>
  <Authenticator v-slot="{ user, signOut }">
    <h1>Hello, Amplify 👋</h1>
    <ul>
      <li v-for="todo in todos" :key="todo.id">{{ todo.content }}</li>
    </ul>
    <button @click="signOut">Sign Out</button>
  </Authenticator>
</template>
